apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: hello
    image: gcr.io/halvard-193600/cloudbuild-actions-test@sha256:ec0ff467859f5162488c2a0a3b3f6cc10ec0cfd4734312d79838cadb50f30600 # {"$kpt-set":"image"}
