apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: hello
    image: gcr.io/halvard-193600/cloudbuild-actions-test@sha256:1b222c446b98c951072022077ba187051c0573914fc7c9e405975562cf6dbde4 # {"$kpt-set":"image"}
