apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: hello
    image: gcr.io/halvard-193600/cloudbuild-actions-test@sha256:0b446726ccfd7652e7b8ecca084f9b725faf999702b18a51a5c3cabf7e9d0893 # {"$kpt-set":"image"}
