apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: hello
    image: gcr.io/halvard-193600/cloudbuild-actions-test@sha256:a37c047f8a4e83723b218e016ec0f929ef05eaa7c2c20af42ad87e16b480b39e # {"$kpt-set":"image"}
