apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: hello
    image: gcr.io/halvard-193600/cloudbuild-actions-test@sha256:ac05bf1c69c0c3a4e17affcaebd8eb6cc91dd4923d1c74b67af04ecf07b70edb # {"$kpt-set":"image"}
