apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: hello
    image: gcr.io/halvard-193600/cloudbuild-actions-test@sha256:76918b9921dbd1c9b1ee9d3c4ee43be55ab9b8c31c7032acb1fd69cec21b0d18 # {"$kpt-set":"image"}
